### ISSUE TITLE
issue with nerdtree and tagbar

### ISSUE THREAD

**Issue by yazgoo** [dhruvasagar/vim-zoom#1]
Thanks for this plugin !

However, when using those to plugins
'jistr/vim-nerdtree-tabs', 'majutsushi/tagbar'
When unzooming, the contents of the tabs are not displayed anymore.

**Comment by dhruvasagar** [comment]
Hi,

Yes that is a known limitation at least for now. In order to keep the code complexity to a minimum for this plugin to work. Since the buffers of those plugins & several others like these are mostly generated buffers and not backed by physical files as such it's hard to recreate them effectively without handling them specially considering which plugin they belong to etc.

In general I would also recommend to not use these buffers in a way to have them present all the time, I think your workflow might be better if you have these open on an as need basis and close them as soon as you're done with your immediate need with them to avoid having them around all the time, that way you also save real estate.

**Comment by yazgoo** [comment]
Hi,

Thanks for your quick answer.
I think you're right anyways, I just disabled autostart for these :)

**Comment by dhruvasagar** [comment]
No problem. I am glad you find this useful.
