### ISSUE TITLE
It restarts :terminal when unzoom

### ISSUE THREAD

**Issue by FCO** [dhruvasagar/vim-zoom#18]

**Comment by dhruvasagar** [comment]
@FCO Since this plugin uses vim sessions to restore the window layout, it's reliant on vim's session handling. Check `:h terminal-session` for some help, if you want some specific custom behavior you may use `term_setrestore()` to try to restore that.

Another option is to use https://github.com/Lenovsky/nuake (I use it), and this allows you to show / hide the terminal window making it easy to keep it running in the background to not disturb vim-zoom.
