### ISSUE TITLE
Showcmd of Control-Modified Keys Changes After Intalling vim-zoom

### ISSUE THREAD

**Issue by austinliuigi** [dhruvasagar/vim-zoom#27]
After installing vim-zoom, when pressing control-modified keys (e.g. <kbd>\<C-w></kbd> or <kbd>\<C-t></kbd>), showcmd shows an unusual sequence.

The expected behavior is for showcmd to show `^` as the control key, but with vim-zoom installed it shows `<80>ü^`

Without vim-zoom installed:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/188366979-009bce6e-80a3-4efe-a1bc-4aed8969cd9c.png">

With vim-zoom installed
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/188366900-ca3afff6-335e-41d0-b564-5d03600d935b.png">

**Comment by dhruvasagar** [comment]
@austinliuigi Is this just by installing vim-zoom or are you zoomed in / out ?

**Comment by austinliuigi** [comment]
@dhruvasagar Yeah just by installing vim-zoom. Not zoomed in or out.

**Comment by austinliuigi** [comment]
It's no issue with the functionality, just an eye sore, really.

**Comment by schnz** [comment]
It's because of the `nmap` definition in `zoom.vim`:

```
  nmap <C-W>m <Plug>(zoom-toggle)
```

The literal `<C-W>` causes this wired representation of the keysequence when `showcmd` is set. Also see https://vi.stackexchange.com/questions/6088/using-c-causes-80%C3%BCd-to-flash-in-the-showcmd-area . There is a helpful comment from Mamrezo:

```
In insert mode, try this: Hit <C-V> and then <C-,> this will insert the sequence of keys Vim tracked from Shell
```

When using the suggested trick, it is possible to declare the `nmap` as follows:

```
" Do not copy & paste the line below! The ^W sequence is the representation of the ETB char (ASCII Code 0x17)
nmap ^Wm <Plug>(zoom-toggle)
``` 

Notice how `<C-W>` becomes `^W`. With this definition, the statusbar correctly shows `^W` without flashing `<80>ü^`.

**Comment by dhruvasagar** [comment]
As of now I am going to ignore this. It's more to do with vim and vim-zoom.
